popcornjs:
  js: [js/popcorn-complete.min.js, js/popcorn-custom.js]
  script:
    {{# page.popcornjs.player }}
    <script>
    var pop = Popcorn.{{page.popcornjs.player}}(
      "player",
      "{{page.popcornjs.video}}"
    );
    </script>
   {{/ page.popcornjs.player }}
